isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/http-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"

service:
  type: ClusterIP
  port: 8060
  targetPort: 8060

containerPort: 8060

serviceAccount:
  name: neonesia-ksa
