isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/http-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://nats:4222"
  # urlDB: "postgresql://service01:SvcN2one1A01@127.0.0.1:5432/cloudreload"
  # chanSizeNATS: "10"

service:
  type: ClusterIP
  port: 8060
  targetPort: 8060

containerPort: 8060

serviceAccount:
  name: neonesia-ksa
# ingress:
#   enabled: false
#   className: ""
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   hosts:
#     - host: chart-example.local
#       paths:
#         - path: /
#           pathType: ImplementationSpecific
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local
