isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/http-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  chanSizeNATS: "100"

serviceAccount:
  name: ""

service:
  type: ClusterIP
  port: 8060
  targetPort: 8060

containerPort: 8060

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false