isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/http-channel
  pullPolicy: IfNotPresent
  tag: "v0.2.9"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  chanSizeNATS: "100"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
 
podAnnotations:
  sidecar.istio.io/inject: "false"

service:
  type: ClusterIP
  port: 8060
  targetPort: 8060

containerPort: 8060

serviceAccount:
  name: neonesia-ksa

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
