isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/http-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"

service:
  type: ClusterIP
  port: 8060
  targetPort: 8060

containerPort: 8060

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false