isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/http-channel
  pullPolicy: IfNotPresent
  tag: "v0.3.0"

config:
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "prod"

service:
  type: ClusterIP
  port: 8060
  targetPort: 8060

containerPort: 8060

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false