isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/config-service
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  chanSizeNATS: "100"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

service:
  type: ClusterIP
  port: 8010
  targetPort: 8010

containerPort: 8010

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
