isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/config-service
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.61.112.3:5432/cloudreload"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "redis2024@CRPStage"


service:
  type: ClusterIP
  port: 8010
  targetPort: 8010

containerPort: 8010

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
