isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/config-service
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@10.61.112.4:5432/cloudreload"
  kafkaBrokers:
  - "redpanda0:9093"
  - "redpanda1:9093"
  kafkaChanSize: "100"

service:
  type: ClusterIP
  port: 8010
  targetPort: 8010

containerPort: 8010

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"
#  sidecar.istio.io/proxyCPU: "100m"
#  sidecar.istio.io/proxyMemory: "128Mi"

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
