apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-07-14T08:00:00Z
data:
  DB_URL: {{ .Values.config.urlDB | quote }}
  NSQ_URL: {{ .Values.config.urlNSQ | quote }}
  MS_URL: {{ .Values.config.urlMS | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ISIMPLE_URL: {{ .Values.config.urlIS | quote }}
  ISIMPLE_AUTH_KEY: {{ .Values.config.authKeyIS | quote }}
  ISIMPLE_ENC_KEY: {{ .Values.config.encKeyIS | quote }}
  ISIMPLE_APP_USER_AGENT: {{ .Values.config.appUserAgent | quote }}
