apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-02-11T10:00:00Z
data:
  DB_URL: {{ .Values.config.urlDB | quote }}
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  KAFKA_CHANNEL_SIZE: {{ .Values.config.kafkaChanSize | quote }}
  RDS_URL: {{ .Values.config.urlRDS | quote }}
  RDS_PASSWD: {{ .Values.config.passwdRDS | quote }}
  ISIMPLE_URL: {{ .Values.config.urlIS | quote }}
  ISIMPLE_AUTH_KEY: {{ .Values.config.authKeyIS | quote }}
  ISIMPLE_ENC_KEY: {{ .Values.config.encKeyIS | quote }}
  ISIMPLE_APP_USER_AGENT: {{ .Values.config.appUserAgent | quote }}