isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/node-manager
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://node:m0DemN0de2o22@nats:4222"
  urlDB: "postgresql://service01:SvcN2one1A01@127.0.0.1:5432/cloudreload"
  addrGRPC: "localhost:8020"
  isTLS: "false"
  groupNode: "KEPOO"
  queueSizeTask: "1000"
  queueSizeMobile:  "2000"

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020

containerPort: 8020

serviceAccount:
  name: neonesia-ksa