isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/node-manager
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://node:m0DemN0de2o22@nats:4222"
  urlDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5432/cloudreload"
  groupNode: "KEPOO"
  queueSizeTask: "1000"
  queueSizeMobile:  "2000"
  chanSizeNATS: "100"
  
sqlproxy: 
  instances: "-instances=cloudreload:asia-southeast2:crp-prod00=tcp:5432"

serviceAccount:
  name: neonesia-ksa