isGCP: false

replicaCount: 1

image:
  repository: nginxreg.dev.neonesia.net/crp/node-manager
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"

service:
  type: ClusterIP
  port: 8590
  targetPort: 8590

containerPort: 8590

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
