isGCP: false

replicaCount: 1

image:
  repository: nginxreg.dev.neonesia.net/crp/node-manager
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://node:m0DemN0de2o22@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  groupNode: "KEPOO"
  maxUSSDTask: "1200"     # := NodeCount * USSDMobile
  maxUSSDMobile:  "1200"  # := NodeCount * USSDMobile
  maxSendSMS: "200"       # := NodeCount * SMSMobile
  maxSendSMSMobile: "200" # := NodeCount * SMSMobile
  chanSizeNATS: "100"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
