isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/node-manager
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5432/cloudreload"
  urlNSQ: "nsq:4150"

service:
  type: ClusterIP
  port: 8590
  targetPort: 8590

containerPort: 8590

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
