isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/ticket-service
  pullPolicy: IfNotPresent
  tag: "v0.8.2"

config:
  urlNATS: "nats://legacy:legacy2020@nats:4222"
  urlIRSDB: "daffina:ezykepoo2021@tcp(182.253.83.213:9211)/avr?parseTime=true"
  urlDB: "postgresql://service01:SvcN2one1A01@127.0.0.1:5432/bank"
  diffTime: "25190"
  logLevel: "DEBUG"

serviceAccount:
  name: neonesia-ksa