isGCP: false
replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/ticket-service
  pullPolicy: IfNotPresent
  tag: "v0.8.2"

config:
  urlIRSDB: "neodev:n3ones!aDEV@tcp(mysql-ext)/avr?parseTime=true" # "irs:m4nd4l4@tcp(172.16.9.18:3307)/avr?parseTime=true"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"
  diffTime: "10"
  logLevel: "DEBUG"
  urlNSQ: "nsq:4150"
  
serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
