isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/ticket-service
  pullPolicy: IfNotPresent
  tag: "v0.8.2"

config:
  urlIRSDB: "daffina:ezykepoo2021@tcp(182.253.83.213:9211)/avr?parseTime=true"
  urlDB: "postgresql://service01:SvcN2one1A01@127.0.0.1:5432/bank"
  diffTime: "25190"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  logLevel: "DEBUG"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
