isGCP: false
replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/ticket-service
  pullPolicy: IfNotPresent
  tag: "v0.8.2"

config:
  urlNATS: "nats://legacy:legacy2020@nats:4222"
  urlIRSDB: "neodev:n3ones!aDEV@tcp(mysql-ext)/avr?parseTime=true" # "irs:m4nd4l4@tcp(172.16.9.18:3307)/avr?parseTime=true"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"
  diffTime: "10"
  logLevel: "DEBUG"
  chanSizeNATS: "100"  

serviceAccount:
  name: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
