apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-manager.fullname" . }}
  labels:
    {{- include "node-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "node-manager.selectorLabels" . | nindent 4 }}