isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/report-batch
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.61.112.3:5432/cloudreload"
  urlSTATDB: "postgres://service01:SvcN2one1A01Prod@10.61.112.3:5433/cloudreload"

serviceAccount:
  name: neonesia-ksa

schedule: "0 21 * * *"
