isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/jabber-replicator
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlIRSDB: ""
  urlOTMDB: ""
  jabberAccounts: 
    - acct: "jabberix.com|node00@jabberix.com|N0d3Ch@n20220"
    - acct: "jabberix.com|node01@jabberix.com|N0d3Ch@n20221"
    - acct: "jabberix.com|node02@jabberix.com|N0d3Ch@n20222"
    - acct: "jabberix.com|node03@jabberix.com|N0d3Ch@n20223"
    - acct: "jabberix.com|node04@jabberix.com|N0d3Ch@n20224"
    - acct: "jabberix.com|node05@jabberix.com|N0d3Ch@n20225"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
