isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/jabber-replicator
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlIRSDB: ""
  urlOTMDB: ""
  jabberAccounts: 
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"
    - acct: "jabber-replicator:password"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false

