apiVersion: v1
kind: Service
metadata:
  name: {{ include "scrape-save-service.fullname" . }}
  labels:
    {{- include "scrape-save-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "scrape-save-service.selectorLabels" . | nindent 4 }}