isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/xsell-service
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@127.0.0.1:5432/cloudreload"
  urlDBXSell: ""
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "stage"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 512Mi
