isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/whatsapp-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.2"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5432/cloudreload"
  whatsappID: "6285717742220@s.whatsapp.net"
  whatsappVer: "0,4,2088"
  logLevel: "DEBUG"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "CRPProd@redis2028"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
