isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/whatsapp-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.2"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"
  whatsappID: "6285717742220@s.whatsapp.net"
  whatsappVer: "0,4,2088"
  logLevel: "DEBUG"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
