isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/whatsapp-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.5"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"
  whatsappID: "6285717742220@s.whatsapp.net"
  whatsappKey: "0,4,2088"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "dev"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
