isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/whatsapp-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.5"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@127.0.0.1:5432/cloudreload"
  whatsappID: "6285717742220@s.whatsapp.net"
  whatsappKey: "0,4,2088"  
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "stage"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi
