isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/order-batch
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@10.61.112.4:5432/cloudreload"
  urlNSQ: "nsq:4150"

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020
  kafkaBrokers:
  - "redpanda:9093"
  kafkaChanSize: "100"

containerPort: 8020

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
