isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/order-batch
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlNSQ: "nsq:4150"

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020

containerPort: 8020

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
