isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/order-batch
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  chanSizeNATS: "100"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"

podAnnotations:
  sidecar.istio.io/inject: "false"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020

containerPort: 8020

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
