isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/order-batch
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.61.112.3:5432/cloudreload"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "stage"

service:
  type: ClusterIP
  port: 8020
  targetPort: 8020

containerPort: 8020

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
