isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/bankticket-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.0"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlPOST: "http://bankticket-service/upload/json"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

service:
  type: ClusterIP
  port: 8040
  targetPort: 8040

containerPort: 8040

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
