isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/bankticket-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlPOST: "http://bankticket-service/upload/json"
  chanSizeNATS: "100"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

service:
  type: ClusterIP
  port: 8040
  targetPort: 8040

containerPort: 8040

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
