isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/bankticket-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.0"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlPOST: "http://bankticket-service/upload/json"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "dev"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

service:
  type: ClusterIP
  port: 8040
  targetPort: 8040

containerPort: 8040

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
