isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/bankticket-service
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5432/cloudreload"
  urlPOST: "http://bankticket-service/upload/json"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "CRPProd@redis2028"

service:
  type: ClusterIP
  port: 8040
  targetPort: 8040

containerPort: 8040

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
