isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/report-batch
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlSTATDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  
serviceAccount:
  name: ""

schedule: "0 21 * * *"
