kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-07-14T08:00:00Z
data:
  DB_URL: {{ .Values.config.urlDB | quote }}
  WHATSAPP_ID: {{ .Values.config.whatsappID | quote }}
  WHATSAPP_KEY: {{ .Values.config.whatsappKey | quote }}
  NSQ_URL: {{ .Values.config.urlNSQ | quote }}
  MS_URL: {{ .Values.config.urlMS | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
