isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/bridge-service
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "dev"

serviceAccount:
  name: ""

service:
  type: ClusterIP
  port: 8010
  targetPort: 8010

containerPort: 8010

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
