isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/bridge-service
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.61.112.3:5432/cloudreload"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "stage"

  urlKC: "keycloak.id.cloudreload.com"
  realmKC: "cloudreload"
  adminNameKC: "systemdjob"
  adminPWKC: "NnSysJob1A01"
  roleIDKC: "e8d91b95-f859-4e44-bc42-717a0bfc75af"
  
  urlHAProxy: "10.184.0.18:5555"
  adminIDHAProxy: "haadmin"
  adminPWHAProxy: "Adm1n2024StageU"

service:
  type: ClusterIP
  port: 8099
  targetPort: 8099

containerPort: 8099

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
