isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/bridge-service
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "dev"

  urlKC: "keycloak-http"
  realmKC: "cloudreload"
  adminNameKC: "systemdjob"
  adminPWKC: "NnSysJob1A01"
  roleIDKC: "39af2fa0-8e70-4766-83bd-93f6d9982e00"

  urlHAProxy: "172.16.200.199:5555"
  adminIDHAProxy: "haadmin"
  adminPWHAProxy: "Adm1n2024U"

serviceAccount:
  name: ""

service:
  type: ClusterIP
  port: 8099
  targetPort: 8099

containerPort: 8099

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi
