isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/isimple-manager
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5432/cloudreload"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "CRPProd@redis2028"
  urlIS: "simpel.indosatooredoo.com"
  authKeyIS: "APPYM8205D04"
  encKeyIS: "OoredooMM!123$"
  appUserAgent: "IMImobile/DealerApp/1.4.9/1/DealerApp"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false  