isGCP: false

replicaCount: 1

image:
  repository: nginxreg.dev.neonesia.net/crp/isimple-manager
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  groupNode: "KEPOO"
  maxUSSDTask: "1200"     # := NodeCount * USSDMobile
  maxUSSDMobile:  "1200"  # := NodeCount * USSDMobile
  maxSendSMS: "200"       # := NodeCount * SMSMobile
  maxSendSMSMobile: "200" # := NodeCount * SMSMobile
  chanSizeNATS: "100"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false