isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/product-service
  pullPolicy: IfNotPresent
  tag: "v0.2.13"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@10.61.112.4:5432/cloudreload"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "CRPProd@redis2028"


serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
