apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "statistic-batch.fullname" . }}
  labels:
    {{- include "statistic-batch.labels" . | nindent 4 }}

spec:
  template:
  schedule: {{ .Values.schedule }}
  concurrencyPolicy: Replace  
  successfulJobsHistoryLimit: 0  
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: "false"      
        spec:
          {{- if .Values.isGCP }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-configmap
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: OnFailure
