{{- if or .Values.ingress.enabled (and .Values.global.ingress.enabled .Values.global.ingress.domain) }}
{{- $servicePort := .Values.service.port -}}
{{- $serviceName := include "hasura.fullname" . -}}
{{- $ingressExtraPaths := .Values.ingress.extraPaths -}}
---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "hasura.fullname" . }}
  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- if or .Values.global.ingress.tls.enabled .Values.ingress.tls.enabled }}
    kubernetes.io/tls-acme: "true"
{{- end }}
  labels:
{{- if .Values.ingress.labels }}
{{ toYaml .Values.ingress.labels | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  rules:
  {{- if .Values.global.ingress.domain }}
  - host: "{{ .Values.ingress.subdomain }}.{{ .Values.global.ingress.domain }}"
    http:
      paths:
        - path: "/"
          backend:
          {{- if $.Values.service.servicename }}
            serviceName: {{ $.Values.service.servicename }}
          {{- else }}
            serviceName: {{ default $serviceName .service }}
          {{- end }}
            servicePort: {{ default $servicePort .servicePort }}
  {{- end }}
  {{- range .Values.ingress.hosts }}
  - host: {{ .name }}
    http:
      paths:
      {{- range $ingressExtraPaths }}
      - path: {{ default "/" .path | quote }}
        backend:
        {{- if $.Values.service.servicename }}
          serviceName: {{ $.Values.service.servicename }}
        {{- else }}
          serviceName: {{ default $serviceName .service }}
        {{- end }}
          servicePort: {{ default $servicePort .port }}
      {{- end }}
      - path: {{ default "/" .path | quote }}
        backend:
        {{- if $.Values.service.servicename }}
          serviceName: {{ $.Values.service.servicename }}
        {{- else }}
          serviceName: {{ default $serviceName .service }}
        {{- end }}
          servicePort: {{ default $servicePort .servicePort }}
  {{- end }}
  {{- if or .tls .Values.ingress.tls.enabled .Values.global.ingress.tls.enabled }}
  tls:
  - hosts:
    {{- if .Values.global.ingress.domain }}
    - {{ .Values.ingress.subdomain }}.{{ .Values.global.ingress.domain }}
    {{- end }}
    {{- range .Values.ingress.hosts }}
    - {{ .name }}
    {{- end }}
    {{- if .tlsSecret }}
    secretName: {{ .tlsSecret }}
    {{- else}}
    secretName: "{{ $serviceName }}-tls-secret"
    {{- end}}
  {{- end }}
{{- end -}}