isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/statistic-batch
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  urlCRDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlSTATDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

schedule: "0 20 * * *"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 1000m
    memory: 1Gi


autoscaling:
  enabled: false
