isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/statistic-batch
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlCRDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5432/cloudreload"
  urlSTATDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5433/cloudreload"

serviceAccount:
  name: neonesia-ksa

schedule: "0 20 * * *"