apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "isimple-call.fullname" . }}
  labels:
    {{- include "isimple-call.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "isimple-call.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "isimple-call.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.isGCP }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
