isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/supplier-service
  pullPolicy: IfNotPresent
  tag: "v0.1.0"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://service01:SvcN2one1A01Prod@127.0.0.1:5432/cloudreload"
  chanSizeNATS: "100"
  kafkaBrokers:
  - "redpanda:9093"
  kafkaChanSize: "100"

sqlproxy: 
  instances: "-instances=cloudreload:asia-southeast2:crp-prod00=tcp:5432"

serviceAccount:
  name: neonesia-ksa

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
