isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/order-service
  pullPolicy: IfNotPresent
  tag: "v0.2.16"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.61.112.3:5432/cloudreload"
  chanSizeNATS: "100"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
