isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/order-service
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  chanSizeNATS: "100"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"

podAnnotations:
  sidecar.istio.io/inject: "false"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
