isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/telegram-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"
  botName: "TG-TEST-KEPOO"
  botVer: "1"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
