isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/telegram-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://legacy:legacy2020@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"
  botName: "TG-TEST-KEPOO"
  botVer: "1"
  chanSizeNATS: "100"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
