isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/telegram-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@127.0.0.1:5432/cloudreload"
  botName: "TG-BANK-KEPOO"
  botVer: "1"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "redis2024@CRPStage"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: false
