isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/telegram-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.31"

serviceAccount:
  name: ""

podAnnotations: 
  sidecar.istio.io/inject: "false"

config:
  urlNATS: "nats://nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"
  botName: "TG-TEST-KEPOO"
  botVer: "1"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80