apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-08-08T08:00:00Z
data:
  DB_URL: {{ .Values.config.urlDB | quote }}
  HTTP_PORT: {{ .Values.service.port | quote }}
  NSQ_URL: {{ .Values.config.urlNSQ | quote }}
  MS_URL: {{ .Values.config.urlMS | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}

  KC_URL: {{ .Values.config.urlKC | quote }}
  KC_REALM: {{ .Values.config.realmKC | quote }}
  KC_ADMIN_NAME: {{ .Values.config.adminNameKC | quote }}
  KC_ADMIN_PW: {{ .Values.config.adminPWKC | quote }}
  KC_ROLE_ID: {{ .Values.config.roleIDKC | quote }}

  HAPROXY_URL: {{ .Values.config.urlHAProxy | quote }}
  HAPROXY_ADMIN_ID: {{ .Values.config.adminIDHAProxy | quote }}
  HAPROXY_ADMIN_PW: {{ .Values.config.adminPWHAProxy | quote }}