apiVersion: v1
kind: Service
metadata:
  name: {{ include "chrome-neonesia.fullname" . }}
  labels:
    {{- include "chrome-neonesia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
  selector:
    {{- include "chrome-neonesia.selectorLabels" . | nindent 4 }}