apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-02-11T10:00:00Z
data:
  DB_URL:  {{ .Values.config.urlDB | quote }}
  DBSTAT_URL:  {{ .Values.config.urlSTATDB | quote }}