apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2021-09-16T00:00:00Z
data:
  NATS_URL: {{ .Values.config.urlNATS }}
  DB_URL:  {{ .Values.config.urlDB }}
