isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/bank-collector
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlPOST: "http://scrape-save-service:8088/upload/json"

serviceAccount:
  name: neonesia-ksa