isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/bank-collector
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.0.96.5:5432/bank"  
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"

serviceAccount:
  name: neonesia-ksa

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podAnnotations:
  sidecar.istio.io/inject: "false"
