isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/bank-collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.3"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/bank?sslmode=disable"  
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"
  testRun: "true"

serviceAccount:
  name: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podAnnotations:
  sidecar.istio.io/inject: "false"

autoscaling:
  enabled: false
