isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/bank-collector
  pullPolicy: IfNotPresent
  tag: "v0.0.3"

config:
  urlDB: "postgres://service01:SvcN2one1A01@10.0.96.5:5432/bank"  
  kafkaBrokers: "redpanda0:9093;redpanda1:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "CRPProd@redis2028"
  testRun: "true"

serviceAccount:
  name: neonesia-ksa

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podAnnotations:
  sidecar.istio.io/inject: "false"
