isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/backend-k8s-287402/bank-collector
  pullPolicy: IfNotPresent
  tag: "v0.1.3"

config:
  urlDB: "postgres://service01:SvcN2one1A01@10.0.96.5:5432/bank"  
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "stage"
  testRun: "true"

serviceAccount:
  name: neonesia-ksa

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

podAnnotations:
  sidecar.istio.io/inject: "false"
