isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/jabber-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "stage"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
