isGCP: false 

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/jabber-channel
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
