isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/jabber-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  chanSizeNATS: "100"
