isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/report-service
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.61.112.3:5432/cloudreload"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "stage"

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

containerPort: 9010

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
