isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/report-service
  pullPolicy: IfNotPresent
  tag: "v0.0.1"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "dev"

service:
  type: ClusterIP
  port: 9010
  targetPort: 9010

containerPort: 9010

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
