isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/h3i-channel
  pullPolicy: IfNotPresent
  tag: "v0.0.14"

config:
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"
  passwdRDS: "redis2024@CRPStage"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
