isGCP: false 

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/h3i-channel
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.14"

#podAnnotations: 
#  sidecar.istio.io/inject: "false"

config:
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis-ext:6379"
  passwdRDS: "redis2022@neo"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
