isGCP: false 

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"

serviceAccount:
  name: ""

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
