isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/billing-service
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Stage@10.61.112.3:5432/cloudreload"
  kafkaBrokers:
  - "redpanda:9093"
  kafkaChanSize: "100"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"