isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/billing-service
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@10.61.112.4:5432/cloudreload"
  kafkaBrokers:
  - "redpanda0:9093"
  - "redpanda1:9093"
  kafkaChanSize: "100"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"  

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi  