isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/billing-service
  pullPolicy: IfNotPresent
  tag: "v0.1.2"

config:
  urlDB: "postgres://service01:SvcN2one1A01Prod@10.61.112.4:5432/cloudreload"
  urlNSQ: "nsq:4150"
  # Message Stream
  urlMS: "nsq:4150"
  # dev, stage, prod
  logLevel: "prod"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"  

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi  