isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/reseller-service
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  chanSizeNATS: "100"
  kafkaBrokers:
  - "redpanda:9093"
  kafkaChanSize: "100"

serviceAccount:
  name: ""

sqlproxy: 
  instances: ""

resources: 
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
