isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/reseller-service
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  urlNSQ: "nsq:4150"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
