isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/reseller-service
  pullPolicy: IfNotPresent
  tag: "v0.1.1"

config:
  urlDB: "postgres://neodev:n3ones!aDEV@postgres-ext:5432/cloudreload?sslmode=disable"
  kafkaBrokers: "redpanda:9093"
  kafkaChanSize: "100"
  urlRDS: "redis:6379"  
  passwdRDS: "redis2022@neo"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources: 
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
