apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2021-09-16T00:00:00Z
data:
  DB_URL:  {{ .Values.config.urlDB }}
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}  
  KAFKA_CHANNEL_SIZE: {{ .Values.config.kafkaChanSize | quote }}
  TEST_RUN: {{ .Values.config.testRun | quote }}
