apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-07-14T08:00:00Z
data:
  DB_URL: {{ .Values.config.urlDB | quote }}
  POST_URL: {{ .Values.config.urlPOST | quote }}
  NSQ_URL: {{ .Values.config.urlNSQ | quote }}
