isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/http-call
  pullPolicy: IfNotPresent
  tag: "v0.3.0"

config:
  urlNSQ: "nsq:4150"

serviceAccount:
  name: neonesia-ksa

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
