isGCP: false

replicaCount: 1

image:
  repository: reg.dev.neonesia.net/crp/
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.1"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  chanSizeNATS: "100"
  kafkaBrokers:
  - "redpanda:9093"
  kafkaChanSize: "100"

podAnnotations:
  sidecar.istio.io/inject: "false"

serviceAccount:
  name: ""

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: false
