isGCP: true

replicaCount: 1

image:
  repository: asia.gcr.io/cloudreload/http-call
  pullPolicy: IfNotPresent
  tag: "v0.2.11"

config:
  urlNATS: "nats://crpDefault:nEoN3iaCRP@nats:4222"
  chanSizeNATS: "100"
  kafkaBrokers:
  - "redpanda:9093"
  kafkaChanSize: "100"

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

serviceAccount:
  name: neonesia-ksa
