apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-02-11T10:00:00Z
data:
  DB_URL: {{ .Values.config.urlDB | quote }}
  BOT_NAME: {{ .Values.config.botName | quote }}
  BOT_VER: {{ .Values.config.botVer | quote }}
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  KAFKA_CHANNEL_SIZE: {{ .Values.config.kafkaChanSize | quote }}
  RDS_URL: {{ .Values.config.urlRDS | quote }}
  RDS_PASSWD: {{ .Values.config.passwdRDS | quote }}
