apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
	creationTimestamp: 2022-07-14T08:00:00Z
data:
  DB_URL: {{ .Values.config.urlDB | quote }}
  BOT_NAME: {{ .Values.config.botName | quote }}
  BOT_VER: {{ .Values.config.botVer | quote }}
  NSQ_URL: {{ .Values.config.urlNSQ | quote }}