apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-02-11T10:00:00Z
data:
  DB_URL:  {{ .Values.config.urlDB | quote }}
  HTTP_PORT: {{ .Values.service.port | quote }}
  KAFKA_BROKERS: {{ .Values.config.kafkaBrokers | quote }}
  KAFKA_CHANNEL_SIZE: {{ .Values.config.kafkaChanSize | quote }}
  RDS_URL: {{ .Values.config.urlRDS | quote }}
  RDS_PASSWD: {{ .Values.config.passwdRDS | quote }}
