apiVersion: batch/v1beta1
kind: Job
metadata:
  name: {{ include "report-batch.fullname" . }}
  labels:
    {{- include "report-batch.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: 0  
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.isGCP }}
          serviceAccountName: {{ .Values.serviceAccount.name }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
              - configMapRef:
                  name: {{ .Release.Name }}-configmap
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
            {{- if .Values.isGCP }}
            - name: cloud-sql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:latest
              command:
                - "/cloud_sql_proxy"
                - "-ip_address_types=PRIVATE"
                - "-instances=backend-k8s-287402:asia-southeast2:pg-bank=tcp:5432"
              securityContext:
                runAsNonRoot: true
            {{- end }}
          restartPolicy: OnFailure
