apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2022-09-16T11:00:00Z
data:
  SERVICE_PORT: {{ .Values.service.port | quote }}
  DB_URL: {{ .Values.config.urlDB | quote }}  
  NSQ_URL: {{ .Values.config.urlNSQ | quote }}
  MS_URL: {{ .Values.config.urlMS | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
