apiVersion: v1
kind: Service
metadata:
  name: {{ include "report-service.fullname" . }}
  labels:
    {{- include "report-service.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "report-service.selectorLabels" . | nindent 4 }}