kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2021-09-16T00:00:00Z
data:
  NATS_URL: {{ .Values.urlNATS }}
  TRACE: {{ .Values.isTrace }}